### PR TITLE
Fix vehicles stopping in the middle of the road

### PR DESCRIPTION
**Pull request by abrahamajb**
Assigned driver peds CruiseWithVehicle task so they won't just sit there in the middle of the road.

### CODE REVIEW

**Review by Michael21107 — APPROVED** [review]

**Comment by Michael21107** [comment]
hey, could you please link the original file? i cant find it

**Comment by abrahamajb** [comment]
This was using the SpawnMP.cs file from 2.0.5 release source code zip, all I could do is re-download it off github and upload it. This fix didn't entirely solve the problem on my end, though. Some additional changes are needed to increase spawn rates however as I very rarely came across vehicles that were actually spawning. Many just had blips but no vehicle.

**Comment by Michael21107** [comment]
i see, 2.0.5 got spawnmp but it seems like the main branch doesn't anymore, it would be amazing if u could make a new pull request

**Comment by abrahamajb** [comment]
https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/archive/refs/tags/2.0.5.zip

**Comment by Michael21107** [comment]
ik 2.0.5 has it, but the current branch doesnt

**Comment by sruckstar** [comment]
I changed the structure a bit and separated the code for spawning cars in traffic and in parking lots. 

In the new version, I used your implementation variant and also expanded the car spawning area to the whole map.

**Pull request closed without merging**
